apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-config
webhooks:
- name: stable.example.com
  rules:
  - operations: ["CREATE"]
    apiGroups: ["stable.example.com"]
    apiVersions: ["v1"]
    resources: ["wsh"]
    scope: "*"
  clientConfig:
    service:
      namespace: default
      name: "webhook-svc"
      path: /crd
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEVENDQXZXZ0F3SUJBZ0lVWHkxN1NZbk4xcXNLK0xTUzRwN05JNHpkejBvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZTXhDekFKQmdOVkJBWVRBa05PTVFzd0NRWURWUVFJREFKSFJERUxNQWtHQTFVRUJ3d0NVMW94RGpBTQpCZ05WQkFvTUJYWnBhRzl2TVF3d0NnWURWUVFMREFOa1pYWXhJREFlQmdOVkJBTU1GM2RsWW1odmIyc3RjM1pqCkxtUmxabUYxYkhRdWMzWmpNUm93R0FZSktvWklodmNOQVFrQkZndDVlVUIyYVhadkxtTnZiVEFlRncweU1qQTIKTWpreE5UVTFNekJhRncweU1qQTNNamt4TlRVMU16QmFNSUdETVFzd0NRWURWUVFHRXdKRFRqRUxNQWtHQTFVRQpDQXdDUjBReEN6QUpCZ05WQkFjTUFsTmFNUTR3REFZRFZRUUtEQVYyYVdodmJ6RU1NQW9HQTFVRUN3d0RaR1YyCk1TQXdIZ1lEVlFRRERCZDNaV0pvYjI5ckxYTjJZeTVrWldaaGRXeDBMbk4yWXpFYU1CZ0dDU3FHU0liM0RRRUoKQVJZTGVYbEFkbWwyYnk1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFESwo3ZEQyYmNudjBkN2ltODAzeks2cSsvaXRIMzFRWWF1ZkYwKytuUmZSNFNoKy9yekJYNkwxdFo5NW0yVGxHbXkwCjRjVVRNSmNsYlY3Z1ZQMVNYTVF2MmxnT1NFRXN5S1EzQjVWOEhzRm1YaGxvNWIxb3V3N0Z3OG5DQXZtSkMzRjUKckR3WDVQVVUvN3lGMXAyL0E0MFIxSlpJZ3F6YjdaQ1l1YW5IZW12MVJYN1Q1ZGVOL01BcWdwNlgzWnZrd2Y3VgpUVjZKSWcyOE1YVUNwZVJndzRUTVNHVDN4ZFRIajByTGhhQ3ZoT1Fsam0wMTgyRER0RFZwaGRYK0FjNThvUkZBCkJaQlZ5VTZGU0g2d1VyRDU0eU5GVFZHYnl5RXM2c29CRTl0NWNQblo0R0FzSm5EMmI2QlFjWUJFTzZRV01QVDcKZGFSZkFHbUl5NVdGeUd4Yzl0a3pBZ01CQUFHamR6QjFNQjBHQTFVZERnUVdCQlJXWjROblB5dTM0MUN0R3R3aApWV3UyOEJjVWtEQWZCZ05WSFNNRUdEQVdnQlJXWjROblB5dTM0MUN0R3R3aFZXdTI4QmNVa0RBUEJnTlZIUk1CCkFmOEVCVEFEQVFIL01DSUdBMVVkRVFRYk1CbUNGM2RsWW1odmIyc3RjM1pqTG1SbFptRjFiSFF1YzNaak1BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUMzOFlUWk0rY1h5Z2hTbG96YUxLbWFKdExvU3h0cExTTjhlR28wSWxSRwpXZkFRdVNORXB2dVplUzhXbmlmTlF0bzRLMFB4QTJLbUJsQ1FaSjFrQ0R6eGxkQzIrbVVPRkFoMjVMWFpsUXhqCkxOSTIxZ2RnbkZMNGRtbDJodGJlQ3VTMFZMdThKbGRLN1VQSWFYMk1SK0lRSVlBRE1OZjdZbzBCeVZKNjBWVnIKQVlERU5iTk93OHlGTklaUlFhWXJBNkJrUEJUSU5ZZ0V0ZkhxSjJ0Ry9ZbktXTDJmTjkvbFhSY3U5eVVPUlhmaAp2YUZBNCt1ZmRDdm9hcTdUeGJST2JzWFRkQ29Kb3g1cmVzdFkrRmp3RTFyTHpjYTNPUEJYZ2ptK1lCdFVNOFFBCit0dXdrbUorSCtQRklaV0QzUjZNRTRNVjZBLy9BcHZ2OUppcTZtMjRxSjdMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-config-mwc
webhooks:
- name: pod-inject.stable.example.com
  rules:
  - operations: ["CREATE"]
    apiGroups: ["*"]
    apiVersions: ["v1"]
    resources: ["*/*"]
    scope: "*"
  clientConfig:
    service:
      namespace: default
      name: "webhook-svc"
      path: /pods
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEVENDQXZXZ0F3SUJBZ0lVWHkxN1NZbk4xcXNLK0xTUzRwN05JNHpkejBvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZTXhDekFKQmdOVkJBWVRBa05PTVFzd0NRWURWUVFJREFKSFJERUxNQWtHQTFVRUJ3d0NVMW94RGpBTQpCZ05WQkFvTUJYWnBhRzl2TVF3d0NnWURWUVFMREFOa1pYWXhJREFlQmdOVkJBTU1GM2RsWW1odmIyc3RjM1pqCkxtUmxabUYxYkhRdWMzWmpNUm93R0FZSktvWklodmNOQVFrQkZndDVlVUIyYVhadkxtTnZiVEFlRncweU1qQTIKTWpreE5UVTFNekJhRncweU1qQTNNamt4TlRVMU16QmFNSUdETVFzd0NRWURWUVFHRXdKRFRqRUxNQWtHQTFVRQpDQXdDUjBReEN6QUpCZ05WQkFjTUFsTmFNUTR3REFZRFZRUUtEQVYyYVdodmJ6RU1NQW9HQTFVRUN3d0RaR1YyCk1TQXdIZ1lEVlFRRERCZDNaV0pvYjI5ckxYTjJZeTVrWldaaGRXeDBMbk4yWXpFYU1CZ0dDU3FHU0liM0RRRUoKQVJZTGVYbEFkbWwyYnk1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFESwo3ZEQyYmNudjBkN2ltODAzeks2cSsvaXRIMzFRWWF1ZkYwKytuUmZSNFNoKy9yekJYNkwxdFo5NW0yVGxHbXkwCjRjVVRNSmNsYlY3Z1ZQMVNYTVF2MmxnT1NFRXN5S1EzQjVWOEhzRm1YaGxvNWIxb3V3N0Z3OG5DQXZtSkMzRjUKckR3WDVQVVUvN3lGMXAyL0E0MFIxSlpJZ3F6YjdaQ1l1YW5IZW12MVJYN1Q1ZGVOL01BcWdwNlgzWnZrd2Y3VgpUVjZKSWcyOE1YVUNwZVJndzRUTVNHVDN4ZFRIajByTGhhQ3ZoT1Fsam0wMTgyRER0RFZwaGRYK0FjNThvUkZBCkJaQlZ5VTZGU0g2d1VyRDU0eU5GVFZHYnl5RXM2c29CRTl0NWNQblo0R0FzSm5EMmI2QlFjWUJFTzZRV01QVDcKZGFSZkFHbUl5NVdGeUd4Yzl0a3pBZ01CQUFHamR6QjFNQjBHQTFVZERnUVdCQlJXWjROblB5dTM0MUN0R3R3aApWV3UyOEJjVWtEQWZCZ05WSFNNRUdEQVdnQlJXWjROblB5dTM0MUN0R3R3aFZXdTI4QmNVa0RBUEJnTlZIUk1CCkFmOEVCVEFEQVFIL01DSUdBMVVkRVFRYk1CbUNGM2RsWW1odmIyc3RjM1pqTG1SbFptRjFiSFF1YzNaak1BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUMzOFlUWk0rY1h5Z2hTbG96YUxLbWFKdExvU3h0cExTTjhlR28wSWxSRwpXZkFRdVNORXB2dVplUzhXbmlmTlF0bzRLMFB4QTJLbUJsQ1FaSjFrQ0R6eGxkQzIrbVVPRkFoMjVMWFpsUXhqCkxOSTIxZ2RnbkZMNGRtbDJodGJlQ3VTMFZMdThKbGRLN1VQSWFYMk1SK0lRSVlBRE1OZjdZbzBCeVZKNjBWVnIKQVlERU5iTk93OHlGTklaUlFhWXJBNkJrUEJUSU5ZZ0V0ZkhxSjJ0Ry9ZbktXTDJmTjkvbFhSY3U5eVVPUlhmaAp2YUZBNCt1ZmRDdm9hcTdUeGJST2JzWFRkQ29Kb3g1cmVzdFkrRmp3RTFyTHpjYTNPUEJYZ2ptK1lCdFVNOFFBCit0dXdrbUorSCtQRklaV0QzUjZNRTRNVjZBLy9BcHZ2OUppcTZtMjRxSjdMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5